# DSBDAL Assignment 6
## Data Analytics III
#### 31128
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv
dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,
Recall on the given dataset

#### Importing Libraries

In [37]:
import pandas as pd
import numpy as np
from array import array
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn import model_selection
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

#### Reading Dataset

In [3]:
df = pd.read_csv('Iris.csv')

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

#### Label Encoding (one hot encoding)

In [6]:
label_encoder = preprocessing.LabelEncoder()

In [8]:
df['Species']= label_encoder.fit_transform(df['Species'])

In [9]:
df['Species'].unique()

array([0, 1, 2])

#### Updated Dataset

In [10]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

#### Naive Bayes Classifier

In [12]:
clf = GaussianNB()

In [26]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [21]:
validation_size = 0.33

In [22]:
seed = 7

In [27]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [38]:
gaussian = GaussianNB()
gaussian.fit(X_train, Y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(Y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, Y_train) * 100, 2)

cm = confusion_matrix(Y_test, Y_pred)
accuracy = accuracy_score(Y_test,Y_pred)
precision =precision_score(Y_test, Y_pred,average='micro')
recall =  recall_score(Y_test, Y_pred,average='micro')
f1 = f1_score(Y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[14  0  0]
 [ 0 18  0]
 [ 0  1 17]]
accuracy_Naive Bayes: 0.980
precision_Naive Bayes: 0.980
recall_Naive Bayes: 0.980
f1-score_Naive Bayes : 0.980
